config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'contact', to: 'pages#contact'
  get 'infos', to: 'pages#infos'
  get 'projects', to: 'pages#projects'
  get 'experiences', to: 'pages#experiences'
  get 'formation', to: 'pages#formation'
  get 'skills', to: 'pages#skills'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def infos
  end

  def projects
  end

  def experiences
  end

  def formation
  end

  def skills
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonCvEnLigne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="main">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h2>Téléphone</h2>
<p>06 18 76 27 04</p>
<h2>Email</h2>
<p>michaelgastal@gmail.com</p>
<h2>Adresse</h2>
<p>11 bis route de la Gare</p>
<p>13570 Barbentane</p>

app/views/pages/experiences.html.erb
<h2>Mon expérience</h2>

app/views/pages/formation.html.erb
<h2>Ma formation</h2>

app/views/pages/home.html.erb
<div class="home-page">

  <div class="profile-card text-center col-lg-3 col-sm-5 col-xs-12 offset-lg-1">

    <div class="profile-main-section light-green-background">
      <div class="round gray-background">
      </div>
      <%= image_tag "https://avatars.githubusercontent.com/u/77100379?v=4", alt: "Avatar of Michael", class: "avatar-xl" %>
      <h2>
        Michaël
        <br>
        Gastal
      </h2>
      <p>
        CONCEPTEUR - DEVELOPPEUR
        <br>
        D'APPLICATIONS WEB
        <br>
        FULL-STACK
      </p>
    </div>

    <div class="social-networks white-background">
      <a href="https://www.linkedin.com/in/michael-gastal" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a href="https://www.github.com/michael-gastal" target="_blank"><i class="fab fa-github"></i></a>
    </div>

  </div>

  <div class="presentation gray-background text-white col-lg-8 col-sm-8 col-xs-12 offset-lg-3 offset-sm-4">
    <h1 class="text-center">Bonjour</h1>
    <h2 class="text-center">
      Je suis Michaël,
      <br>
      votre Concepteur - Développeur
      <br>
      d'applications Web full-stack
    </h2>
    <h2 class="text-center">💻</h2>
    <p>Formé par Le Wagon Marseille, j'ai obtenu ma <strong>certification de niveau VI (bac +4)</strong>.</p>
    <p>Après 10 semaines de formation intensive, je maîtrise à présent <strong>la POO, l'architecture MVC, Ruby, Ruby on Rails, JavaScript, Html, CSS et Bootstrap</strong>.</p>
    <p>Je conçois et développe des applications Web de A à Z en mettant le <strong>client au coeur de la problématique</strong>.</p>
    <p>Je maîtrise <strong>Git & Github</strong> et je sais déployer sur <strong>Heroku</strong>.</p>
    <p>Je sais gérer les bases de données en <strong>SQL, MySQL et PostgreSQL</strong>.</p>
    <p>Je sais gérer les <strong>autorisations</strong> et les <strong>authentifications</strong>, notamment avec les gems <strong>Devise et Pundit</strong>.</p>
    <p>Ayant à coeur de proposer un <strong>code propre et fonctionnel</strong>, je pratique le <strong>TDD</strong> et le <strong>refactoring</strong>.</p>
  </div>

</div>

app/views/pages/infos.html.erb
<p>Je suis développeur full-stack</p>

app/views/pages/projects.html.erb
<h2>Mes projets</h2>

app/views/pages/skills.html.erb
<h2>Mes compétences</h2>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-dark navbar-cv sticky-top">
  <%= link_to "Michaël Gastal", root_path, class: "home-link text-white" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="right-links collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <%= link_to "A propos de moi", infos_path, class: "navbar-link text-white" %>
      <%= link_to "Mes projets", projects_path, class: "navbar-link text-white" %>
      <%= link_to "Mon expérience", experiences_path, class: "navbar-link text-white" %>
      <%= link_to "Ma formation", formation_path, class: "navbar-link text-white" %>
      <%= link_to "Mes compétences", skills_path, class: "navbar-link text-white" %>
      <%= link_to "Me contacter", contact_path, class: "navbar-link text-white" %>
    </div>
  </div>
</div>